version: '3'

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: fapi
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 123456789
      POSTGRES_HOST: localhost
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    
  web:
    build: .
    command: sh -c "uvicorn app.main:api --port=8080"
    
    links:
      - db
   