version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: fapi
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 123456789
      # POSTGRES_HOST: localhost   
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    
  web:
    build: .
    command: 'uvicorn app.main:api --port=8080'
    depends_on:
      - db
        # condition: service_healthy
    ports:
      - 8080:8080
volumes:
  postgres_data: