version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456789}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    restart: unless-stopped

  
  web:
    container_name: web
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://dev@localhost/fapi
      - SECRET_KEY=secret_key



volumes:
  postgres_data:
